[Do not merge] Bump xgboost to 1.2
aws/amazon-sagemaker-examples pull request #1562
Opened 2020-09-22 22:33 UTC by edwardjkim

*Description of changes:*

Bumping xgboost version to 1.2-1. **Do not merge until https://github.com/aws/sagemaker-python-sdk/pull/1899 is merged and released to PyPI.**

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-02 20:13 UTC, edwardjkim commented
@iyerr3 Python SDK v2 now has image URIs for 1.2-1 and the notebooks are ready. Please review and merge if they look okay (I don't have merge permissions).

2020-10-07 19:26 UTC, aaronmarkham requested changes
Please refer the template for upgrade/downgrade approach that won't mess up the kernel.
Also, it would help to make the required version of SDK very clear in the intro/prerequisites section of the notebooks.

2020-10-07 19:26 UTC, aaronmarkham commented on introduction_to_amazon_algorithms/xgboost_abalone/xgboost_abalone_dist_script_mode.ipynb
> +    "!{sys.executable} -m pip install -qU awscli boto3 \"sagemaker==2.*\""
Please refer the [template for upgrade/downgrade approach](https://github.com/aws/amazon-sagemaker-examples/blob/master/template.ipynb) that won't mess up the kernel.

2020-10-28 03:45 UTC, edwardjkim commented on introduction_to_amazon_algorithms/xgboost_abalone/inference.py
> +        return ','.join(str(x) for x in predictions[0])
The default content type for the XGBoost estimator was changed to `text/csv` in SDK v2. JSON is still supported but it requires overriding the content type by passing an additional argument to the estimator, and I think changing the content type in the script is simpler.

2020-10-28 03:45 UTC, edwardjkim commented on introduction_to_amazon_algorithms/xgboost_abalone/xgboost_inferenece_script_mode.ipynb
> +    "!{sys.executable} -m pip install -qU awscli boto3 \"sagemaker==2.*\""
Thanks for catching this. Removed.

2020-10-28 03:45 UTC, edwardjkim commented on introduction_to_amazon_algorithms/xgboost_abalone/xgboost_parquet_input_training.ipynb
> +    "!python -m pip install pyarrow==0.16  # upgrade to 0.16 for xgboost 1.2-1"
Changed to `%pip`.

2020-12-08 03:18 UTC, edwardjkim commented
@aaronmarkham Sorry about the delayed follow up. I was waiting for SDK v2 to become available on Studio and/or Mead, and now that it's available, I've tested the the notebooks again on Studio and made some changes accordingly. Could you take another look when you get a chance? Thanks.

2020-12-16 17:19 UTC, aaronmarkham approved these changes

2020-12-16 17:19 UTC, merged