upgrade notebook to SDK v2
aws/amazon-sagemaker-examples pull request #1576
Opened 2020-09-26 23:29 UTC by danabens

* run sagemaker-upgrade-v2 utility
* black format
* verify successful run with Python 3 Data Science kernel via Studio
* use recently added delete experiment SDK method
* add team contact info
* pin versions of packages referenced by `pip install`

2020-09-29 16:48 UTC, jerrypeng7773 approved these changes

2020-09-29 17:19 UTC, ajaykarpur requested changes
Since the SDK is currently pinned to v1 on Notebook Instances and Studio, you'll also need to include this line in the notebook for now:
```
!{sys.executable} -m pip install "sagemaker>2"
```

2020-10-01 00:05 UTC, danabens commented
> Since the SDK is currently pinned to v1 on Notebook Instances and Studio, you'll also need to include this line in the notebook for now:
> 
> ```
> !{sys.executable} -m pip install "sagemaker>2"
> ```

added

2020-10-01 21:19 UTC, danabens commented
changed to `!{sys.executable} -m pip install --upgrade sagemaker`

2020-10-02 18:44 UTC, ajaykarpur approved these changes

2020-10-02 18:45 UTC, merged