fixing multi-instance and multi-GPU PyTorch DistributedDataParallel training to use all GPUs
aws/amazon-sagemaker-examples pull request #1666
Opened 2020-10-29 07:40 UTC by muhyun

*Issue #, if available:*

None

*Description of changes:*

The existing pytorch distributed training example does not spawn workers per GPU, which results in utilizing 1 GPU on each instance. So, this is a fix to utilize all the GPUs by spawning workers.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-09 03:10 UTC, muhyun commented
Please get this reviewed.

2020-12-15 02:09 UTC, mchoi8739 commented
Please update the metadata at the end of the notebook to use the newer PT kernel.

```
 "metadata": {
  "kernelspec": {
   "display_name": "conda_pytorch_p36",
   "language": "python",
   "name": "conda_pytorch_p36"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  },
```

2020-12-15 02:10 UTC, mchoi8739 requested changes

2020-12-15 02:10 UTC, mchoi8739 commented on sagemaker-python-sdk/pytorch_mnist/pytorch_mnist.ipynb
> +    "                    framework_version='1.6.0',\n",
Update the estimator to use SM pysdk v2 params

```
from sagemaker.pytorch import PyTorch

estimator = PyTorch(entry_point='mnist.py',
                    role=role,
                    framework_version='1.6.0',
                    py_version='py3',
                    instance_count=2,
                    instance_type='ml.c4.xlarge',
                    hyperparameters={
                        'epochs': 6,
                        'backend': 'gloo'
                    })
```

2022-02-07 17:08 UTC, closed without merging