Small fix and notebook formatting - PCA
aws/amazon-sagemaker-examples pull request #1715
Opened 2020-11-09 15:53 UTC by vivekmadan2

Sagemaker syntax change fix and notebook formatting.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-17 04:05 UTC, mabunday requested changes

2020-11-17 04:05 UTC, mabunday commented on introduction_to_amazon_algorithms/pca_mnist/pca_mnist.ipynb
> +    "    if subplot == None:\n",
Please change this to `if subplot is None:`

2020-11-18 16:16 UTC, mabunday approved these changes

2020-11-18 19:38 UTC, aaronmarkham approved these changes

2020-11-18 21:53 UTC, merged