Object2vec cleaned
aws/amazon-sagemaker-examples pull request #1751
Opened 2020-11-15 22:42 UTC by vivekmadan2

Sagemaker syntax change fix and notebook formatting.

@reviewer: **Please do not merge**
1. Waiting for legal approval regarding hosting dataset on S3 bucket.
2. Name of the data bucket would change to jump-start and needs to be reflected in this PR.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-11-17 01:54 UTC, mabunday requested changes

2020-11-17 01:54 UTC, mabunday commented on introduction_to_amazon_algorithms/object2vec_movie_recommendation/object2vec_movie_recommendation.ipynb
> +    "        if obj.key[-1] == \"/\":\n",
Is `obj.key` the filename? I'm assuming then that the `if` condition is checking if it's a directory then. In this case, I think we can use `if obj.key.endswith("/"):` instead.

2020-11-17 01:54 UTC, mabunday commented on introduction_to_amazon_algorithms/object2vec_movie_recommendation/object2vec_movie_recommendation.ipynb
> +    "                # print(row)\n",
Should this line and the next be removed since they're commented out anyway?

2020-11-17 01:54 UTC, mabunday commented on introduction_to_amazon_algorithms/object2vec_movie_recommendation/object2vec_movie_recommendation.ipynb
> +    "            # print(row)\n",
Should this line be removed?

2020-11-17 01:54 UTC, mabunday commented on introduction_to_amazon_algorithms/object2vec_movie_recommendation/object2vec_movie_recommendation.ipynb
> +    "            # if i < 10:\n",
Please remove commented out lines if they are not going to be used.

2020-11-18 03:53 UTC, vivekmadan2 commented
Legal: Dataset can not be used.

2020-11-18 03:53 UTC, closed without merging