Update explaining_customer_churn_model.ipynb to align with SDK-2.x
aws/amazon-sagemaker-examples pull request #1828
Opened 2020-12-04 18:02 UTC by sermolin

CSV type, RealTimePredictor => Predictor

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-04 20:32 UTC, SomnathSI approved these changes
Looks good!

2020-12-04 23:26 UTC, SomnathSI requested changes
In the new `Predictor` API, the default value for `serializer` is the `IdentitySerializer` which has content_type='application/octet-stream'. We should add `serializer=sagemaker.serializers.CSVSerializer()` to the Predictor. ie 

```
self.predictor = Predictor(
    endpoint_name=endpoint,
    sagemaker_session=sagemaker_session,
    serializer=sagemaker.serializers.CSVSerializer(),
    content_type="text/csv",
    accept="text/csv"
)
```

2020-12-16 00:37 UTC, hsl89 approved these changes
Tested end to end

2020-12-16 00:40 UTC, SomnathSI approved these changes

2020-12-16 00:56 UTC, merged