Update sagemaker debugger TF actions notebook to use built-in actions
aws/amazon-sagemaker-examples pull request #1964
Opened 2021-02-02 00:26 UTC by ndodda-amazon

*Issue #, if available:*

*Description of changes:*
SageMaker Debugger now offers built-in actions. This TF example notebook has been updated to use built-in actions to be automatically invoked when the stalled training rule detects inactivity in the training job. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-02-02 18:56 UTC, seanpmorgan commented on sagemaker-debugger/tensorflow_action_on_rule/detect_stalled_training_job_and_actions.ipynb
>     "cell_type": "markdown",
<p>nit: <code>uses these actions</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/1964/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2021-02-02 18:57 UTC, seanpmorgan requested changes
Small typo then LGTM

2021-02-03 20:11 UTC, ndodda-amazon commented on sagemaker-debugger/tensorflow_action_on_rule/detect_stalled_training_job_and_actions.ipynb
>     "cell_type": "markdown",
Thanks, fixed.

2021-02-03 22:02 UTC, seanpmorgan approved these changes
LGTM

2021-02-03 22:02 UTC, merged