[documentation] fixed missing cells
aws/amazon-sagemaker-examples pull request #1977
Opened 2021-02-06 01:47 UTC by IvyBazan

*Issue #, if available:*
#1491 
*Description of changes:*
Removed collapsed TOC metadata entry that prevented viewing as expected in JupyterLab

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-02-12 22:56 UTC, larroy approved these changes

2021-02-12 23:08 UTC, arengoh approved these changes

2021-02-12 23:08 UTC, arengoh approved these changes

2021-02-13 01:22 UTC, arengoh requested changes
[](autopilot/sagemaker_autopilot_direct_marketing.ipynb)

2021-02-13 03:40 UTC, paul-cb approved these changes
Approved.

2021-02-13 03:40 UTC, merged