Modified docker and notebook files
aws/amazon-sagemaker-examples pull request #2096
Opened 2021-03-24 10:31 UTC by RominaUQ

*Issue #, if available:*

*Description of changes:*
- on Docker file, the URL for get.pip is updated. The old url is no longer working.
-  on the notebook, the 'sagemaker-studio-image-build' is used to allow the build of Docker from inside Sagemaker Studio.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-16 00:04 UTC, mchoi8739 requested changes

2021-04-16 00:04 UTC, mchoi8739 commented on advanced_functionality/multi_model_bring_your_own/multi_model_endpoint_bring_your_own.ipynb
> +    "**Note**: the section of code that build the container, has been changed to allow enable build of a Docker container in Amazon SageMaker Studio, using 'sagemaker-studio-image-build'.\n",
**Note**: To build a Docker container in Amazon SageMaker Studio, we use the 'sagemaker-studio-image-build' package and its `sm-docker build` command.

2021-04-16 00:06 UTC, mchoi8739 commented on advanced_functionality/multi_model_bring_your_own/multi_model_endpoint_bring_your_own.ipynb
>      "\n",
<p>Add the following cell to install MXNet if not exist:</p><p> </p><pre class="ql-syntax" spellcheck="false">import pip

def import_or_install(package):
    try:
        __import__(package)
    except ImportError:
        pip.main(['install', package])  
        
import_or_install('mxnet')
</pre>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/2096/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2024-05-28 03:37 UTC, zhaoqizqwang commented
Closing this PR since it was created a long time ago and didn't pass all the checks. Feel free to open a new pull request instead.

2024-05-28 03:37 UTC, closed without merging