Update SMMP GPT2 sample
aws/amazon-sagemaker-examples pull request #3433
Opened 2022-05-27 21:35 UTC by haohanchen-yagao

*Issue #, if available:*

*Description of changes: Update SMMP GPT2 script with the latest changes, the main changes are:

- Removed fp16 folder as fp16 related functions/wrappers are integrated into SMMP code base now. 
- Updated the memory tracker
- Removed private functions/arguments from public example
- Updated transformer version
- Updated Pytorch version to 1.11 in notebooks

Note: This PR shouldn't be merged until changes to SMMP is released.

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-sagemaker-examples/blob/master/CONTRIBUTING.md) doc and adhered to the example notebook best practices
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-sagemaker-examples/blob/master/README.md)
- [x] I have tested my notebook(s) and ensured it runs end-to-end
- [ ] I have linted my notebook(s) and code using `tox -e black-format,black-nb-format`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-11 18:54 UTC, YangFei1990 submitted a review, later dismissed

2022-10-12 00:23 UTC, mchoi8739 requested changes

2022-10-12 00:23 UTC, mchoi8739 commented on training/distributed_training/pytorch/model_parallel/gpt-j/11_train_gptj_smp_tensor_parallel_notebook.ipynb
> +    "# import IPythonfp16\n",
```suggestion
    "# import IPython\n",
```

2022-10-12 00:23 UTC, mchoi8739 commented on training/distributed_training/pytorch/model_parallel/gpt2/smp-train-gpt-simple.ipynb
> +    "- `sharded_data_parallel_checkpoint.py`: This contains the checkpoint utils for sharded dat parallelism\n",
```suggestion
    "- `sharded_data_parallel_checkpoint.py`: This contains checkpoint util functions for sharded data parallelism.\n",
```

2022-10-12 00:23 UTC, mchoi8739 commented on training/distributed_training/pytorch/model_parallel/gpt-j/11_train_gptj_smp_tensor_parallel_notebook.ipynb
>      "! pip install -qU \"sagemaker>=2,<3\"\n",
<p>Suggest to change the intro sentence:</p><p> </p><p>You'll learn how to train the GPT-J model with tensor parallelism on the GLUE sst2 dataset.</p><p> </p><p>--&gt;</p><p> </p><p>You'll learn how to run FP16 training of the GPT-J model with tensor parallelism on the GLUE sst2 dataset.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/3433/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2022-10-12 00:23 UTC, mchoi8739 commented on training/distributed_training/pytorch/model_parallel/gpt-j/11_train_gptj_smp_tensor_parallel_notebook.ipynb
>      "! pip install -qU \"sagemaker>=2,<3\"\n",
<p>Change the title to:</p><p> </p><h3>Create a SageMaker PyTorch Estimator</h3><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/3433/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='54'/>

2022-10-12 00:23 UTC, mchoi8739 commented on training/distributed_training/pytorch/model_parallel/gpt2/smp-train-gpt-simple.ipynb
>     "cell_type": "markdown",
<p>Same suggestion for the intro paragraph:</p><p> </p><p>You'll learn how to train the GPT-2 model with SageMaker's model parallelism.</p><p>--&gt;</p><p>You'll learn how to run FP16 training of the GPT-2 model with SageMaker's model parallelism.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/3433/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2022-10-12 00:23 UTC, mchoi8739 commented on training/distributed_training/pytorch/model_parallel/gpt2/smp-train-gpt-simple.ipynb
>     "cell_type": "markdown",
<p>Change HuggingFace to PyTorch in the title and the text.</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/3433/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='29'/>

2022-10-12 00:25 UTC, mchoi8739 commented
Run `black-nb -l 100` to pass the code formatting test.

2022-10-12 23:04 UTC, mchoi8739 approved these changes

2022-10-12 23:06 UTC, YangFei1990 approved these changes

2022-10-13 22:00 UTC, aaronmarkham approved these changes

2022-10-13 22:15 UTC, merged