Smddp MNIST example update
aws/amazon-sagemaker-examples pull request #3448
Opened 2022-06-07 20:42 UTC by apoorvtintin

*Issue #, if available:*

*Description of changes:*

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

- [ ] I have read the [CONTRIBUTING](https://github.com/aws/amazon-sagemaker-examples/blob/master/CONTRIBUTING.md) doc and adhered to the example notebook best practices
- [ ] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-sagemaker-examples/blob/master/README.md)
- [ ] I have tested my notebook(s) and ensured it runs end-to-end
- [ ] I have linted my notebook(s) and code using `tox -e black-format,black-nb-format`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-08 17:51 UTC, Zha0q1 commented
@apoorvtintin Thanks for the PR! Code changes look good to me!
Would you help update the notebook too? There's some outdated info e.g.
1. "This notebook example shows how to use smdistributed.dataparallel with PyTorch in SageMaker using MNIST dataset." (introduce smddp backend explicitly)
2. "The [data parallel](https://docs.aws.amazon.com/sagemaker/latest/dg/data-parallel.html) feature in this library is a distributed data parallel training framework for PyTorch, TensorFlow, and MXNet. (remove mxnet)"
3. "The training script is very similar to a PyTorch training script you might run outside of SageMaker, but modified to run with the smdistributed.dataparallel library. This library's PyTorch client provides an alternative to PyTorch's native DDP." (we DO use pytorch native ddp now)
etc.

2022-06-08 17:51 UTC, Zha0q1 requested changes
@apoorvtintin Thanks for the PR! Code changes look good to me!
Would you help update the notebook too? There's some outdated info e.g.
1. "This notebook example shows how to use smdistributed.dataparallel with PyTorch in SageMaker using MNIST dataset." (introduce smddp backend explicitly)
2. "The [data parallel](https://docs.aws.amazon.com/sagemaker/latest/dg/data-parallel.html) feature in this library is a distributed data parallel training framework for PyTorch, TensorFlow, and MXNet. (remove mxnet)"
3. "The training script is very similar to a PyTorch training script you might run outside of SageMaker, but modified to run with the smdistributed.dataparallel library. This library's PyTorch client provides an alternative to PyTorch's native DDP." (we DO use pytorch native ddp now)
etc.

2022-06-08 18:23 UTC, mchoi8739 submitted a review, later dismissed

2022-06-09 20:24 UTC, apoorvtintin commented
> @apoorvtintin Thanks for the PR! Code changes look good to me! Would you help update the notebook too? There's some outdated info e.g.
> 
>     1. "This notebook example shows how to use smdistributed.dataparallel with PyTorch in SageMaker using MNIST dataset." (introduce smddp backend explicitly)
> 
>     2. "The [data parallel](https://docs.aws.amazon.com/sagemaker/latest/dg/data-parallel.html) feature in this library is a distributed data parallel training framework for PyTorch, TensorFlow, and MXNet. (remove mxnet)"
> 
>     3. "The training script is very similar to a PyTorch training script you might run outside of SageMaker, but modified to run with the smdistributed.dataparallel library. This library's PyTorch client provides an alternative to PyTorch's native DDP." (we DO use pytorch native ddp now)
>        etc.

Thanks for the review and comments Zhaoqi and Miyoung, I have updated the vocabulary for the notebook to reflect our new smddp backend. 
Please let me know if any more changes are needed.

2022-06-10 00:26 UTC, Zha0q1 commented on training/distributed_training/pytorch/data_parallel/mnist/pytorch_smdataparallel_mnist_demo.ipynb
>      "# Part 1: Distributed data parallel MNIST training with PyTorch and SageMaker distributed\n",
<p>nit: "PyTorch distributed library" -&gt; "PyTorch DDP (Distributed Data Parallel)"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/3448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2022-06-10 00:26 UTC, Zha0q1 commented on training/distributed_training/pytorch/data_parallel/mnist/pytorch_smdataparallel_mnist_demo.ipynb
>      "# Part 1: Distributed data parallel MNIST training with PyTorch and SageMaker distributed\n",
<p>similarly "PyTorch DDP"</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/3448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2022-06-10 00:26 UTC, Zha0q1 approved these changes
LGTM, thank you!

2022-06-15 16:54 UTC, jkroll-aws commented on training/distributed_training/pytorch/data_parallel/mnist/pytorch_smdataparallel_mnist_demo.ipynb
>      "# Part 1: Distributed data parallel MNIST training with PyTorch and SageMaker distributed\n",
<p>Nit: <code>Pytorch</code> -&gt; <code>PyTorch</code>   </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/3448/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2024-05-28 03:49 UTC, zhaoqizqwang commented
Closing this PR since it was created a long time ago and didn't pass all the checks. Feel free to open a new pull request instead.

2024-05-28 03:49 UTC, closed without merging