Add Visual Inspection Automation with Pre-trained Amazon SageMaker Models to README.md
aws/amazon-sagemaker-examples pull request #3605
Opened 2022-09-19 19:33 UTC by tao2020

*Issue #, if available:*

*Description of changes:*
Add Visual Inspection Automation with Pre-trained Amazon SageMaker Models example to README.md
This new example was merged on 9/16/2022 in the introduction_to_applying_machine_learning folder. 

*Testing done:*

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-sagemaker-examples/blob/master/CONTRIBUTING.md) doc and adhered to the example notebook best practices
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-sagemaker-examples/blob/master/README.md)
- [x] I have tested my notebook(s) and ensured it runs end-to-end
- [x] I have linted my notebook(s) and code using `black-nb -l 100 {path}/{notebook-name}.ipynb`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-09-19 21:11 UTC, aaronmarkham requested changes
This looks fine, but can you rebase & flatten your commits down to one?

2022-09-20 18:06 UTC, atqy approved these changes

2022-09-20 18:07 UTC, atqy commented
> This looks fine, but can you rebase & flatten your commits down to one?

No worries about this - we automatically squash all his commits into one when we merge so I think it's good to go, unless there is something I am missing.

2022-09-20 18:33 UTC, atqy approved these changes

2022-09-20 18:36 UTC, merged