Add example notebook for PDP analysis with SageMaker Clarify
aws/amazon-sagemaker-examples pull request #3752
Opened 2023-01-24 01:10 UTC by oyangz

*Issue #, if available:* https://issues.amazon.com/issues/P53689304

*Description of changes:*
New Jupyter notebook that shows how to create Partial Dependency Plots (PDP) with Sagemaker Clarify with and without SHAP. 

*Testing done:*
Ran the notebook end to end and confirmed there were no errors.

## Merge Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your pull request._

- [x] I have read the [CONTRIBUTING](https://github.com/aws/amazon-sagemaker-examples/blob/master/CONTRIBUTING.md) doc and adhered to the example notebook best practices
- [x] I have updated any necessary documentation, including [READMEs](https://github.com/aws/amazon-sagemaker-examples/blob/master/README.md)
- [x] I have tested my notebook(s) and ensured it runs end-to-end
- [x] I have linted my notebook(s) and code using `black-nb -l 100 {path}/{notebook-name}.ipynb`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-02-06 21:44 UTC, goswamig commented
@larroy

2023-02-07 06:50 UTC, goswamig commented
@larroy

2023-02-07 23:03 UTC, larroy commented
<p>Minor comments but LGTM</p>

2023-02-07 23:03 UTC, larroy approved these changes
minor comments, LGTM.

2023-02-08 10:19 UTC, bilalaws requested changes
Thanks for the PR. Added some suggestions. All except one are about improving readability. The remaining one is about changing a stale hyperlink.

2023-02-08 10:19 UTC, bilalaws commented on sagemaker-clarify/fairness_and_explainability/explainability_with_pdp.ipynb
> +    "    save_local_shap_values=True,\n",
Is this necessary? The only role of SHAP is to select 5 most important features (globally). So we do not need to save local SHAP vals.

2023-02-08 10:19 UTC, bilalaws commented on sagemaker-clarify/fairness_and_explainability/explainability_with_pdp.ipynb
> +    "    num_samples=15,\n",
Let us remove `num_samples` from here and let the constructor use the default value. If not, we should explain what this parameter does.

2023-02-08 10:19 UTC, bilalaws commented on sagemaker-clarify/fairness_and_explainability/explainability_with_pdp.ipynb
> +    "The Kernel SHAP algorithm requires a [baseline for explainability](https://docs.aws.amazon.com/sagemaker/latest/dg/clarify-feature-attribute-shap-baselines.html), also known as a background data
Let us also add: The parameter `agg_method` specifies how the per-instance feature importance should be aggregated over the dataset to compute the overall (global) feature importance. For more details see [Amazon AI Fairness and Explainability Whitepaper](https://pages.awscloud.com/rs/112-TZM-766/images/Amazon.AI.Fairness.and.Explainability.Whitepaper.pdf).

2023-02-08 10:19 UTC, bilalaws commented on sagemaker-clarify/fairness_and_explainability/explainability_with_pdp.ipynb
> +    "    explainability_config=[pdp_config, shap_config],\n",
`logs=False`

2023-02-08 18:46 UTC, oyangz commented on sagemaker-clarify/fairness_and_explainability/explainability_with_pdp.ipynb
> +    "IPython.display.HTML(filename=\"explainability-report.html\")"
We are inferring feature types here. I believe currently line plots are the only option for both categorical and numerical features in the report. I will look into this and track it in a separate SIM, and can work on it in another CR.

2023-02-09 10:28 UTC, bilalaws approved these changes

2023-02-09 10:28 UTC, bilalaws submitted a review, later dismissed

2023-02-10 22:39 UTC, rdamazon commented on sagemaker-clarify/fairness_and_explainability/explainability_with_pdp.ipynb
> +{
<p>can you add plt.show() here</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/3752/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2023-02-10 22:39 UTC, rdamazon commented on sagemaker-clarify/fairness_and_explainability/explainability_with_pdp.ipynb
> +{
<p>can you add plt.show() here? </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/aws/amazon-sagemaker-examples/pull/3752/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='10'/>

2023-02-13 18:30 UTC, merged